- hosts: localhost
  vars:
    vm_name: "ISE-WINDOWS-2019-CIS-HARDENED"
    vm_subnet: "subnet-e26556a4"
    vm_type: "t2.medium"
    vm_role: "instance_profile_for_cis_test"
    vm_sg_id: "sg-03f10038db28367ae"
    admin_user: administrator
    admin_password: "KPQy9sY37@YaCH!C"
  gather_facts: no
  roles:
  - role: odp-ansible-windows2019

- hosts: base_image
  tasks:
  - name: Check connectivity
    win_ping:
